// <auto-generated />
using System;
using MOZ_UPGRADE.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MOZ_UPGRADE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104200145_MakeTwoFACodeNullable")]
    partial class MakeTwoFACodeNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MOZ_UPGRADE.Models.IndividualKyc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Accept_Marketing_Communication")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Address_2")
                        .HasColumnType("longtext");

                    b.Property<string>("Approval_Status")
                        .HasColumnType("longtext");

                    b.Property<string>("BVN_No")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Company_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Company_No")
                        .HasColumnType("longtext");

                    b.Property<string>("Company_Registration")
                        .HasColumnType("longtext");

                    b.Property<string>("Company_Representative")
                        .HasColumnType("longtext");

                    b.Property<string>("Contact_Business_Relation")
                        .HasColumnType("longtext");

                    b.Property<string>("Contact_Type")
                        .HasColumnType("longtext");

                    b.Property<string>("Correspondence_Type")
                        .HasColumnType("longtext");

                    b.Property<string>("Country_Region_Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("County")
                        .HasColumnType("longtext");

                    b.Property<string>("Currency_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Customer_Category")
                        .HasColumnType("longtext");

                    b.Property<bool>("Data_Protection_Consent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Date_of_Birth")
                        .HasColumnType("longtext");

                    b.Property<string>("Date_of_Incorporation")
                        .HasColumnType("longtext");

                    b.Property<string>("Date_of_Last_Interaction")
                        .HasColumnType("longtext");

                    b.Property<string>("E_Mail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("E_Mail_2")
                        .HasColumnType("longtext");

                    b.Property<string>("Employer_Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("Exclude_from_Segment")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Fax_No")
                        .HasColumnType("longtext");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Format_Region")
                        .HasColumnType("longtext");

                    b.Property<string>("High_Risk_Low_Risk")
                        .HasColumnType("longtext");

                    b.Property<string>("Home_Page")
                        .HasColumnType("longtext");

                    b.Property<string>("ID_Expiry_Date")
                        .HasColumnType("longtext");

                    b.Property<string>("ID_Number")
                        .HasColumnType("longtext");

                    b.Property<string>("IntegrationCustomerNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Job_Title")
                        .HasColumnType("longtext");

                    b.Property<string>("Language_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("LastDateTimeModified")
                        .HasColumnType("longtext");

                    b.Property<string>("Last_Date_Attempted")
                        .HasColumnType("longtext");

                    b.Property<string>("Last_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Legal_Representative")
                        .HasColumnType("longtext");

                    b.Property<string>("Marital_Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Means_of_Identification")
                        .HasColumnType("longtext");

                    b.Property<bool>("Minor")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mobile_Phone_No")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Name_2")
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext");

                    b.Property<string>("Next_Task_Date")
                        .HasColumnType("longtext");

                    b.Property<string>("Next_of_Kin_Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Next_of_Kin_Phone_No")
                        .HasColumnType("longtext");

                    b.Property<string>("Next_of_Kin_Relationship")
                        .HasColumnType("longtext");

                    b.Property<string>("Next_of_Kin_Title")
                        .HasColumnType("longtext");

                    b.Property<string>("Next_of_kin_DOB")
                        .HasColumnType("longtext");

                    b.Property<string>("Next_of_kin_Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Next_of_kin_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Next_of_kin_address")
                        .HasColumnType("longtext");

                    b.Property<string>("No")
                        .HasColumnType("longtext");

                    b.Property<string>("Occupation")
                        .HasColumnType("longtext");

                    b.Property<string>("Officers_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Onboarding_Date")
                        .HasColumnType("longtext");

                    b.Property<string>("Organizational_Level_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Other_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PEP_Status")
                        .HasColumnType("longtext");

                    b.Property<bool>("Parental_Consent_Received")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone_No")
                        .HasColumnType("longtext");

                    b.Property<string>("Post_Code")
                        .HasColumnType("longtext");

                    b.Property<bool>("Privacy_Blocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RM_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("RM_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Registration_Number")
                        .HasColumnType("longtext");

                    b.Property<string>("Religion_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Religion_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Salesforce_ID")
                        .HasColumnType("longtext");

                    b.Property<string>("Salesperson_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Salutation_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Search_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Sector")
                        .HasColumnType("longtext");

                    b.Property<string>("Sector_Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Segments")
                        .HasColumnType("longtext");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext");

                    b.Property<string>("Source_of_Funds")
                        .HasColumnType("longtext");

                    b.Property<string>("Stage")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Subsegments")
                        .HasColumnType("longtext");

                    b.Property<string>("Tax_ID")
                        .HasColumnType("longtext");

                    b.Property<string>("Territory_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VAT_Registration_No")
                        .HasColumnType("longtext");

                    b.Property<string>("odata_etag")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IndividualKycs");
                });

            modelBuilder.Entity("MOZ_UPGRADE.Models.Users", b =>
                {
                    b.Property<string>("strid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("Contact_No")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsTwoFAEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TwoFACode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TwoFACodeExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("strid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MOZ_UPGRADE.Models.IndividualKyc", b =>
                {
                    b.HasOne("MOZ_UPGRADE.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
